const express = require('express');
var fs = require('fs');
var multer  = require('multer');
var upload = multer({ dest: 'uploads/' }); //setting the default folder for multer


const app = express();
app.use(function(req, res, next) { 

    res.header("Access-Control-Allow-Origin", '*'); 
    
    res.header("Access-Control-Allow-Credentials", true); 
    
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS'); 
    
    res.header("Access-Control-Allow-Headers", 'Origin,X-Requested-With,Content-Type,Accept,content-type,application/json'); 
    
    next();
  });

app.get('/' ,(req, res) => res.send('ready to go'));
//other imports and code will go here
app.post('/upload',upload.single('fileData'), (req, res,next) => {
  logger.info(req.file);//this will be automatically set by multer
  logger.info(req.body);
  //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
  fs.readFile(req.file.path,(err, contents)=> {
   if (err) {
   console.log('Error: ', err);
  }else{
   console.log('File contents ',contents);
  }
 });
});


const port = 3001;

app.listen(port, () => console.log(`Server started on port ${port}`));